config/routes.rb
Rails.application.routes.draw do
  root 'doctors#index'

    resources :patients

    resources :doctors do
      resources :appointments 
    end
    resources :appointments do
      resources :comments
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  has_many :comments, through: :patients
  has_many :comments, through: :doctors
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

app/models/patient.rb
class Patient < ApplicationRecord
has_many :appointments, dependent: :destroy
has_many :doctors, through: :appointments

def full_name
  "#{self.first_name} #{self.last_name}"
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_doctor
  before_action :set_patient, only: [:new, :create, :update]
  def index
    @appointments = @doctor.appointments.all
  end

  def new
    @appointment = @doctor.appointments.new
  end

  def create
    @appointment = @doctor.appointments.new(appointment_params)
    if @appointment.save
      redirect_to doctor_path(@doctor)
    else
      render :new
    end
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.find(params[:id])
    if @appointment.update(appointment_params)
      redirect_to doctor_path(@doctor)
    else
      render :edit
    end
  end

  def destroy
    @doctor.appointments.find(params[:id]).destroy
    redirect_to physicians_path
  end

  def show
   @patient = Patient.find(params[:id])
   @appointment = Appointment.find(params[:id])
  end

  private

  def set_patient
    @patient = Patient.all - @doctor.patients
  end

  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end

  def appointment_params
    params.require(:appointment).permit(:date, :patient_id, :doctor_id)
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  #set_*model* is private method that loads in called index automatically
 def index
    @doctors = Doctor.all
  end
  
 def new
    @doctor = Doctor.new
  end
  
 def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to doctors_path
    else
      render :new
    end
  end
  
 def show
   #before_action
 end
  
 def edit
   #before_action
 end
  
 def update
    @doctor = Doctor.find(params[:id])
    if @doctor.update(doctor_params)
      redirect_to doctors_path
    else
      render :edit
    end
  end
  
 def destroy
    @doctor.destroy
    redirect_to doctors_path
  end
  
 private
  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :specialty)
  end
  
 def set_doctor
    @doctor = Doctor.find(params[:id])
  end

 end
 

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  #set_*model* is private method that loads in called index automatically
 def index
    @patients = Patient.all
  end
  
 def new
    @patient = Patient.new
  end
  
 def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to patients_path
    else
      render :new
    end
  end
  
 def show
   #before_action
 end
  
 def edit
   #before_action
 end
  
 def update
    @patient = Patient.find(params[:id])
    if @patient.update(patient_params)
      redirect_to patients_path
    else
      render :edit
    end
  end
  
 def destroy
    @patient.destroy
    redirect_to patients_path
  end
  
 private
  def patient_params
    params.require(:patient).permit(:first_name, :last_name)
  end
  
 def set_patient
    @patient = Patient.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/index.html.erb
 <nav>
    <div class="nav-wrapper teal lighten-4">
      <ul class="right hide-on-med-and-down teal lighten-4">
        <li><%= link_to 'Go Back', doctor_path(@doctor), class: "waves-effect waves-light btn" %></li>
      </ul>
    </div>
  </nav>
<h3>CURRENT APPOINTMENTS</h3>
<% @appointments.each do |appt| %>
  <%= appt.patient.first_name %>
  <%= appt.patient.last_name %>
  <br>
  <%= appt.date %>
  <br>
  <br>
  <br>
<% end %>

app/views/appointments/new.html.erb
 <nav>
    <div class="nav-wrapper teal lighten-4">
      <ul class="right hide-on-med-and-down teal lighten-4">
        <li><%= link_to 'Go Back', doctor_path(@doctor), class: "waves-effect waves-light btn" %></li>
      </ul>
    </div>
  </nav>
<h3>REQUEST APPOINTMENT</h3>
  <div class="row">
    <div class="input-field col s6">
      <%= form_with(model: [@doctor, @appointment], local: true) do |f| %>
        <%= f.label :patient  %>
        <%= f.select :patient_id, Patient.all.collect { |u| [u.full_name, u.id] } %>
        <%= f.date_field :date %>
        <%= f.submit nil, class: "btn waves-effect waves-light btn" %>
      <% end %>
    </div>
  </div>
  

 

app/views/appointments/show.html.erb
<nav>
    <div class="nav-wrapper teal lighten-4">
      <ul class="right hide-on-med-and-down teal lighten-4">
        <li><%= link_to 'Go Back', patient_path(@patient), class: "waves-effect waves-light btn" %></li>
      </ul>
    </div>
  </nav>
<h5><%= "Patient: #{@patient.full_name}"%></h5>
<h5><%= "Appointment with: #{@doctor.full_name}, #{@doctor.specialty}"%></h5>
<p><%= "Scheduled : #{@appointment.date}"%></p>
<hr>
<%= link_to "Comments", appointment_comment_path(@appointment) %>

app/views/doctors/edit.html.erb
 <nav>
    <div class="nav-wrapper teal lighten-4">
      <ul class="right hide-on-med-and-down teal lighten-4">
        <li><%= link_to 'Go Back', @doctor, class: "waves-effect waves-light btn" %></li>
      </ul>
    </div>
  </nav>
  <h3>EDIT DOCTOR</h3>
<%= form_with(model: @doctor, local: true, class: "input-field col s6" ) do |f| %>
<div class="field">
  <%= f.text_field :first_name, required: true, placeholder: "First Name" %>
  <br>
  <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  <br>
  <%= f.text_field :specialty, required: true, placeholder: "Specialty" %>
</div>
  <%= f.submit nil, class: "btn waves-effect waves-light" %>

<% end %>

app/views/doctors/index.html.erb
<%= render 'layouts/nav_doctors' %>
<h3>DOCTORS</h3>
<hr/>
<ul>
  <% @doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.full_name, doctor %>
    </li>
<% end %>
</ul>

app/views/doctors/new.html.erb
 <nav>
    <div class="nav-wrapper teal lighten-4">
      <ul class="right hide-on-med-and-down teal lighten-4">
        <li><%= link_to 'Go Back', doctors_path, class: "waves-effect waves-light btn" %></li>
      </ul>
    </div>
  </nav>
  <h3>ADD DOCTOR</h3>
<%= form_with(model: @doctor, local: true, class: "ui form" ) do |f| %>
<div class="field">
  <%= f.text_field :first_name, required: true, placeholder: "First Name" %>
  <br>
  <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  <br>
  <%= f.text_field :specialty, required: true, placeholder: "Specialty" %>
</div>
  <%= f.submit nil, class: "btn waves-effect waves-light" %>

<% end %>

app/views/doctors/show.html.erb
 <nav>
    <div class="nav-wrapper teal lighten-4">
      <ul class="right hide-on-med-and-down teal lighten-4">
        <li><%= link_to 'Go Back', doctors_path, class: "waves-effect waves-light btn" %></li>
        <li><%= link_to 'Request Appointment', new_doctor_appointment_path(@doctor), class: "waves-effect waves-light btn" %></li>
        <li><%= link_to 'View Appointments', doctor_appointments_path(@doctor), class: "waves-effect waves-light btn" %></li>
        <li><%= link_to 'Edit Doctor', edit_doctor_path(@doctor), class: "waves-effect waves-light btn" %></li>
        <li><%= link_to 'Delete Doctor', doctor_path(@doctor), method: :delete, class: "waves-effect waves-light btn" %></li>
      </ul>
    </div>
  </nav>
<h3><%= @doctor.full_name.upcase %></h3>
<h5><%= @doctor.specialty %></h5>

app/views/layouts/_nav_doctors.html.erb
  <nav>
    <div class="nav-wrapper teal lighten-4">
      <ul class="right hide-on-med-and-down teal lighten-4">
        <li><%= link_to 'New Doctor', new_doctor_path, class: "waves-effect waves-light btn" %></li>
        <li><%= link_to 'Patients', patients_path, class: "waves-effect waves-light btn" %></li>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorsOffice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/_nav_patients.html.erb
  <nav>
    <div class="nav-wrapper teal lighten-4">
      <ul class="right hide-on-med-and-down teal lighten-4">
        <li><%= link_to 'New Patient', new_patient_path, class: "waves-effect waves-light btn" %></li>
        <li><%= link_to 'Doctors', doctors_path, class: "waves-effect waves-light btn" %></li>
      </ul>
    </div>
  </nav>

app/views/patients/edit.html.erb
 <nav>
    <div class="nav-wrapper teal lighten-4">
      <ul class="right hide-on-med-and-down teal lighten-4">
        <li><%= link_to 'Go Back', @patient, class: "waves-effect waves-light btn" %></li>
      </ul>
    </div>
  </nav>
  <h3>EDIT PATIENT</h3>
<%= form_with(model: @patient, local: true, class: "ui form" ) do |f| %>
<div class="field">
  <%= f.text_field :first_name, required: true, placeholder: "First Name" %>
  <br>
  <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  <br>
</div>
  <%= f.submit nil, class: "btn waves-effect waves-light" %>

<% end %>

app/views/patients/index.html.erb
<%= render 'nav_patients' %>
<h3>PATIENTS</h3>
<hr/>
<ul>
  <% @patients.each do |patient| %>
    <li>
      <%= link_to patient.full_name, patient %>
    </li>
<% end %>
</ul>

app/views/patients/new.html.erb
 <nav>
    <div class="nav-wrapper teal lighten-4">
      <ul class="right hide-on-med-and-down teal lighten-4">
        <li><%= link_to 'Go Back', @patient, class: "waves-effect waves-light btn" %></li>
      </ul>
    </div>
  </nav>
  <h3>NEW PATIENT</h3>
<%= form_with(model: @patient, local: true, class: "ui form" ) do |f| %>
<div class="field">
  <%= f.text_field :first_name, required: true, placeholder: "First Name" %>
  <br>
  <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  <br>
</div>
  <%= f.submit nil, class: "btn waves-effect waves-light" %>

<% end %>

app/views/patients/show.html.erb
 <nav>
    <div class="nav-wrapper teal lighten-4">
      <ul class="right hide-on-med-and-down teal lighten-4">
        <li><%= link_to 'Go Back', patients_path, class: "waves-effect waves-light btn" %></li>
        <li><%= link_to 'Edit Patient', edit_patient_path(@patient), class: "waves-effect waves-light btn" %></li>
        <li><%= link_to 'Delete Patient', patient_path(@patient), method: :delete, class: "waves-effect waves-light btn" %></li>
      </ul>
    </div>
  </nav>
<h3><%= @patient.full_name.upcase %></h3>
 <div class="divider"></div>
 <h6>Current Appointments:</h6>
 <% @patient.appointments.each do |appt| %>
    <br>
    <li>
      <%= link_to "#{appt.date} with #{appt.doctor.full_name}", doctor_appointment_path(appt.doctor) %>
    </li>
  <% end %>